apiVersion: v1
kind: Service
metadata:
    name: notificationmicroservice
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    loadBalancerIP: 10.224.0.26
    ports:
      - port: 80
    selector:
        app: notificationmicroservice
